spring:
  application:
    name: primeira-api-bootcamp
  datasource:
    url: jdbc:mysql://localhost:3306/my_database
    username: my_username
    password: my_password
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
